// <auto-generated />
namespace BBBZ.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class remove_require_Access : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_require_Access));
        
        string IMigrationMetadata.Id
        {
            get { return "201612291758455_remove_require_Access"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
