// <auto-generated />
namespace BBBZ.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class tiny_changes_in_some_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tiny_changes_in_some_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201612170637150_tiny_changes_in_some_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
