// <auto-generated />
namespace BBBZ.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class fix_bug_ong_customFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_bug_ong_customFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201612251332051_fix_bug_ong_customFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
