// <auto-generated />
namespace BBBZ.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class add_name_prop_to_MenuTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_name_prop_to_MenuTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201611191916494_add_name_prop_to_MenuTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
