// <auto-generated />
namespace BBBZ.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class majors_changes_for_db_stracture : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(majors_changes_for_db_stracture));
        
        string IMigrationMetadata.Id
        {
            get { return "201611181543525_majors_changes_for_db_stracture"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
