// <auto-generated />
namespace BBBZ.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class add_access_to_menu_tabel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_access_to_menu_tabel));
        
        string IMigrationMetadata.Id
        {
            get { return "201612222026231_add_access_to_menu_tabel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
