// <auto-generated />
namespace BBBZ.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class require_title_for_ViewLevel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(require_title_for_ViewLevel));
        
        string IMigrationMetadata.Id
        {
            get { return "201612291754089_require_title_for_ViewLevel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
