// <auto-generated />
namespace BBBZ.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class fix_db_after_the_big_changes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_db_after_the_big_changes));
        
        string IMigrationMetadata.Id
        {
            get { return "201611191033454_fix_db_after_the_big_changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
