// <auto-generated />
namespace BBBZ.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class fix_permission_tabel2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_permission_tabel2));
        
        string IMigrationMetadata.Id
        {
            get { return "201612251030013_fix_permission_tabel2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
