// <auto-generated />
namespace BBBZ.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class add_some_annotation_to_Datamodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_some_annotation_to_Datamodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201611080817059_add_some_annotation_to_Datamodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
