// <auto-generated />
namespace BBBZ.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class I_dont_know_why_database_whant_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(I_dont_know_why_database_whant_update));
        
        string IMigrationMetadata.Id
        {
            get { return "201612220722119_I_dont_know_why_database_whant_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
