// <auto-generated />
namespace BBBZ.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class onDeleteCascade_for_custom : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(onDeleteCascade_for_custom));
        
        string IMigrationMetadata.Id
        {
            get { return "201612251258454_onDeleteCascade_for_custom"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
