// <auto-generated />
namespace BBBZ.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class add_message_attachment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_message_attachment));
        
        string IMigrationMetadata.Id
        {
            get { return "201701010847545_add_message_attachment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
