// <auto-generated />
namespace BBBZ.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class fix_permission : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_permission));
        
        string IMigrationMetadata.Id
        {
            get { return "201701021848541_fix_permission"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
